language: python

python:
  - "3.7-dev"  # 3.7 development branch

env:
    JWT_SECRET_KEY="HS256"

install:
  - pip install -r requirements.txt
  - pip install coveralls

addons:
  - postgresql:"9.6"

before_script:
  - psql -c "CREATE DATABASE flask_api;" -U postgres
  - psql -c "CREATE DATABASE test_db;" -U postgres

script:
  - pytest
  - coverage run --source=app -m unittest && coverage report

after_success:
  - coveralls 