"""empty message

Revision ID: 2d0298c41882
Revises: 484d8ce1e069
Create Date: 2019-07-16 14:15:15.931326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d0298c41882'
down_revision = '484d8ce1e069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('amount', sa.Integer(), nullable=True))
    op.drop_column('payments', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('payments', 'amount')
    # ### end Alembic commands ###
