"""empty message

Revision ID: 484d8ce1e069
Revises: 53301fb65ee1
Create Date: 2019-07-16 13:35:48.386262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '484d8ce1e069'
down_revision = '53301fb65ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('shortcode', sa.Integer(), nullable=True),
    sa.Column('msisdn', sa.Integer(), nullable=True),
    sa.Column('commandid', sa.String(length=255), nullable=True),
    sa.Column('billrefnumber', sa.String(length=255), nullable=True),
    sa.Column('refno', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('bucketlists')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bucketlists',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('shortcode', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('msisdn', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('commandid', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('billrefnumber', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('refno', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='bucketlists_pkey')
    )
    op.drop_table('payments')
    # ### end Alembic commands ###
